"""
Pine Script Generator
Export strategy to TradingView Pine Script v5

SUPPORTED INDICATORS (22):
=========================

MOMENTUM INDICATORS (11):
- RSI: Relative Strength Index - Oversold/Overbought signals
- MACD: Moving Average Convergence Divergence - Trend following momentum
- Stochastic: Stochastic Oscillator - Momentum with K/D lines
- CCI: Commodity Channel Index - Cyclical trends
- MFI: Money Flow Index - Volume-weighted RSI
- ROC: Rate of Change - Price momentum
- VROC: Volume Rate of Change - Volume momentum
- RVI: Relative Vigor Index - Vigor of price movement
- Awesome_Oscillator: Bill Williams AO - Market momentum
- Momentum: Simple price momentum
- Candlestick_Patterns: Hammer, Shooting Star, Engulfing patterns

TREND INDICATORS (5):
- EMA_50/200/12/26: Exponential Moving Average - Trend direction
- Triple_EMA: Three EMAs for trend confirmation
- ADX: Average Directional Index - Trend strength with DI+/DI-
- SuperTrend: ATR-based trend indicator
- Ichimoku: Cloud-based trend system (Tenkan, Kijun, Senkou)

VOLATILITY INDICATORS (3):
- Bollinger_Bands: Price envelope with standard deviation
- ATR: Average True Range - Volatility measurement
- Donchian: Highest high / Lowest low channels

VOLUME INDICATORS (2):
- Volume_MA: Volume Moving Average - Volume trend
- OBV: On Balance Volume - Cumulative volume flow

SUPPORT/RESISTANCE (1):
- Pivot_Points: Classic pivot points (PP, R1, S1)

ADVANCED INDICATORS (2):
- Fibonacci: Retracement levels (38.2%, 50%, 61.8%)
- ICT_Concepts: Fair Value Gap, Premium/Discount zones

FILTERS AVAILABLE (5):
=====================
- ADX Filter: Trend strength filter (adx_val > threshold)
- Volume Filter: Volume spike filter (volume > MA * multiplier)
- MA Trend Filter: Price vs Moving Average (close > ma_trend)
- ATR Volatility Filter: Minimum volatility (atr_val > min)
- Long-term Trend Filter: Price vs EMA (close > ema_trend)

FEATURES:
=========
- Weighted signal scoring system
- Threshold-based entries (% of total weight)
- Position switching (Long ↔ Short)
- Risk management (SL%, RR ratio)
- Visual signals and plots
- 100% synchronized with Python backtesting
"""

from strategy_models import Strategy, PineScriptExport
from typing import List, Optional, Dict, Any
from datetime import datetime


class PineScriptGenerator:
    """Generate Pine Script code from strategy"""
    
    @staticmethod
    def generate(strategy: Strategy, backtest_result: Optional[Dict[str, Any]] = None, version: Optional[str] = None) -> PineScriptExport:
        """
        Generate Pine Script v5 code from strategy
        
        Args:
            strategy: Strategy object with indicators, filters, and risk management
            backtest_result: Optional backtest results to include in header
            version: Optional strategy version (defaults to "1.0.0")
            
        Returns:
            PineScriptExport with:
            - code: Complete Pine Script v5 code
            - strategy_name: Name of the strategy
            - indicators_used: List of indicators with their configs
            - version: Strategy version
            - backtest_info: Backtest results if provided
            
        Generated Code Structure:
        1. Header (strategy name, version, description, backtest results)
        2. Indicators section (all enabled indicators)
        3. Filters section (ADX, Volume, MA, ATR, Trend)
        4. Signal Logic (weighted scoring, threshold-based)
        5. Entry/Exit Logic (SL/TP, position switching)
        6. Plotting (signals, weights, indicator lines)
        """
        indicators_used = []
        filters_used = []
        code_parts = []
        
        # Get strategy version
        strategy_version = version or "1.0.0"
        
        # Get filters early for use in header
        filters = strategy.filters
        
        # Build header with strategy info
        header_lines = [
            f"// ==================== STRATEGY INFO ====================",
            f"// Strategy Name: {strategy.name}",
            f"// Strategy Version: {strategy_version}",
            f"// Generated by: Combo Optimizer v1.4",
            f"// Generated Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            f"// Description: {strategy.description or 'Custom strategy'}",
            f"",
            f"// ==================== CONFIGURATION ====================",
            f"// Indicators Used: {len([i for i in strategy.indicators if i.enabled])}",
            f"// Filters Enabled: {sum([filters.enable_adx, filters.enable_volume, filters.enable_ma_filter, filters.enable_atr_filter, filters.enable_trend_filter])}",
            f"// Signal Threshold: {strategy.signal_logic.threshold_percent}%",
            f"// Risk Management: SL={strategy.risk_management.stop_loss_percent}% | RR={strategy.risk_management.reward_ratio}:1",
            f"// Initial Capital: ${strategy.risk_management.capital:,.0f}",
        ]
        
        # Add backtest results if available
        if backtest_result:
            header_lines.extend([
                f"",
                f"// ==================== BACKTEST RESULTS ====================",
                f"// Total Trades: {backtest_result.get('total_trades', 0)}",
                f"// Winning Trades: {backtest_result.get('winning_trades', backtest_result.get('wins', 0))}",
                f"// Losing Trades: {backtest_result.get('losing_trades', backtest_result.get('losses', 0))}",
                f"// Win Rate: {backtest_result.get('win_rate', 0):.2f}%",
                f"// Profit: {backtest_result.get('total_profit_pct', backtest_result.get('profit_pct', 0)):.2f}%",
                f"// Profit Factor: {backtest_result.get('profit_factor', 0):.2f}",
                f"// Max Drawdown: {backtest_result.get('max_drawdown', backtest_result.get('draw_down', 0)):.2f}%",
                f"// Sharpe Ratio: {backtest_result.get('sharpe_ratio', backtest_result.get('sharpe', 0)):.2f}",
            ])
            if backtest_result.get('long_trades') is not None:
                header_lines.append(f"// Long Trades: {backtest_result.get('long_trades', 0)} | Short Trades: {backtest_result.get('short_trades', 0)}")
        
        header_lines.extend([
            f"",
            f"// ==================== PINE SCRIPT CODE ====================",
            f""
        ])
        
        code_parts.append('\n'.join(header_lines))
        
        # Pine Script version and strategy declaration
        code_parts.append(f'''//@version=5
strategy("{strategy.name}", overlay=true, 
         default_qty_type=strategy.percent_of_equity, 
         default_qty_value={strategy.risk_management.risk_percent},
         initial_capital={strategy.risk_management.capital},
         currency=currency.USD)
''')
        
        # Indicator declarations
        indicator_vars = {}
        code_parts.append("\n// ==================== INDICATORS ====================")
        
        for idx, ind in enumerate(strategy.indicators):
            if not ind.enabled:
                continue
            
            ind_type = ind.type
            ind_id = f"{ind_type.lower()}_{idx}"
            indicators_used.append(f"{ind_type}({ind.config})")
            
            code = PineScriptGenerator._generate_indicator_code(
                ind_type, ind.config, ind_id
            )
            code_parts.append(code)
            indicator_vars[ind_id] = {
                'type': ind_type,
                'bullish_var': f"{ind_id}_bull",
                'bearish_var': f"{ind_id}_bear",
                'weight': ind.weight
            }
        
        # Filters (already defined above)
        filter_conditions = []
        
        # Document active filters
        code_parts.append("\n// ==================== FILTERS ====================")
        active_filters = []
        
        if filters.enable_adx:
            active_filters.append(f"ADX > {filters.adx_threshold}")
        if filters.enable_volume:
            active_filters.append(f"Volume > MA * {filters.volume_threshold}")
        if filters.enable_ma_filter:
            active_filters.append(f"Price vs MA({filters.ma_period})")
        if filters.enable_atr_filter:
            active_filters.append(f"ATR > {filters.min_atr}")
        if filters.enable_trend_filter:
            active_filters.append(f"Price vs EMA({filters.trend_ma})")
        
        if active_filters:
            code_parts.append(f"// Active Filters: {', '.join(active_filters)}")
            filters_used = active_filters.copy()
        else:
            code_parts.append("// No filters enabled")
        
        if filters.enable_adx:
            code_parts.append(f'''
// ADX Filter
[di_plus, di_minus, adx_val] = ta.dmi(14, 14)
adx_filter = adx_val > {filters.adx_threshold}''')
            filter_conditions.append("adx_filter")
        
        if filters.enable_volume:
            code_parts.append(f'''
// Volume Filter
vol_ma = ta.sma(volume, 20)
vol_filter = volume > vol_ma * {filters.volume_threshold}''')
            filter_conditions.append("vol_filter")
        
        if filters.enable_ma_filter:
            code_parts.append(f'''
// MA Trend Filter
ma_trend = ta.sma(close, {filters.ma_period})''')
        
        if filters.enable_atr_filter:
            code_parts.append(f'''
// ATR Volatility Filter
atr_val = ta.atr(14)
atr_filter = atr_val > {filters.min_atr}''')
            filter_conditions.append("atr_filter")
        
        if filters.enable_trend_filter:
            code_parts.append(f'''
// Long-term Trend Filter
ema_trend = ta.ema(close, {filters.trend_ma})''')
        
        # Signal Logic with Weights
        code_parts.append("\n// ==================== SIGNAL LOGIC ====================")
        
        # Calculate total weight
        total_weight = sum(v['weight'] for v in indicator_vars.values())
        
        # Bullish calculation
        bullish_parts = []
        bearish_parts = []
        
        for ind_id, ind_info in indicator_vars.items():
            weight = ind_info['weight']
            contribution = weight / total_weight * 100
            
            code_parts.append(f"// {ind_info['type']} contributes {contribution:.2f}%")
            bullish_parts.append(f"({ind_info['bullish_var']} ? {weight} : 0)")
            bearish_parts.append(f"({ind_info['bearish_var']} ? {weight} : 0)")
        
        code_parts.append(f'''
// Weighted signal calculation
total_weight = {total_weight}
bullish_weight = {' + '.join(bullish_parts)}
bearish_weight = {' + '.join(bearish_parts)}

bullish_percent = bullish_weight / total_weight * 100
bearish_percent = bearish_weight / total_weight * 100

// Threshold: {strategy.signal_logic.threshold_percent}%
var bool long_signal = false
var bool short_signal = false
long_signal := bullish_percent >= {strategy.signal_logic.threshold_percent}
short_signal := bearish_percent >= {strategy.signal_logic.threshold_percent}''')
        
        # Apply filters
        if filter_conditions or filters.enable_ma_filter or filters.enable_trend_filter:
            code_parts.append("\n// Apply filters")
            
            all_filters = filter_conditions.copy()
            
            if filters.enable_ma_filter:
                code_parts.append("long_signal := long_signal and close > ma_trend")
                code_parts.append("short_signal := short_signal and close < ma_trend")
            
            if filters.enable_trend_filter:
                code_parts.append("long_signal := long_signal and close > ema_trend")
                code_parts.append("short_signal := short_signal and close < ema_trend")
            
            if all_filters:
                filters_combined = " and ".join(all_filters)
                code_parts.append(f"long_signal := long_signal and {filters_combined}")
                code_parts.append(f"short_signal := short_signal and {filters_combined}")
        
        # Entry/Exit Logic
        code_parts.append(f'''
// ==================== ENTRY/EXIT ====================
// Risk Management
sl_percent = {strategy.risk_management.stop_loss_percent}
rr_ratio = {strategy.risk_management.reward_ratio}

// Calculate SL and TP prices
var float long_sl = na
var float long_tp = na
var float short_sl = na
var float short_tp = na

// Long Entry
if long_signal and strategy.position_size == 0
    long_sl := close * (1 - sl_percent / 100)
    long_tp := close + (close - long_sl) * rr_ratio
    strategy.entry("Long", strategy.long)
    strategy.exit("Long Exit", "Long", stop=long_sl, limit=long_tp)

// Short Entry
if short_signal and strategy.position_size == 0
    short_sl := close * (1 + sl_percent / 100)
    short_tp := close - (short_sl - close) * rr_ratio
    strategy.entry("Short", strategy.short)
    strategy.exit("Short Exit", "Short", stop=short_sl, limit=short_tp)

// Position Switch - Long to Short
if long_signal and strategy.position_size < 0
    strategy.close("Short")
    long_sl := close * (1 - sl_percent / 100)
    long_tp := close + (close - long_sl) * rr_ratio
    strategy.entry("Long", strategy.long)
    strategy.exit("Long Exit", "Long", stop=long_sl, limit=long_tp)

// Position Switch - Short to Long
if short_signal and strategy.position_size > 0
    strategy.close("Long")
    short_sl := close * (1 + sl_percent / 100)
    short_tp := close - (short_sl - close) * rr_ratio
    strategy.entry("Short", strategy.short)
    strategy.exit("Short Exit", "Short", stop=short_sl, limit=short_tp)''')
        
        # Plotting
        code_parts.append('''
// ==================== PLOTTING ====================
// Plot signals
plotshape(long_signal, "Long Signal", shape.triangleup, location.belowbar, color.green, size=size.small)
plotshape(short_signal, "Short Signal", shape.triangledown, location.abovebar, color.red, size=size.small)

// Plot weight percentages (optional)
plot(bullish_percent, "Bullish %", color=color.new(color.green, 70))
plot(bearish_percent, "Bearish %", color=color.new(color.red, 70))
hline(''' + f'{strategy.signal_logic.threshold_percent}, "Threshold", color=color.gray, linestyle=hline.style_dashed)')
        
        # Summary comment
        code_parts.append(f'''

// ==================== SUMMARY ====================
// Indicators: {', '.join([f"{v['type']}(weight={v['weight']})" for v in indicator_vars.values()])}
// Filters: {', '.join(filters_used) if filters_used else 'None'}
// Total Indicators: {len(indicator_vars)}
// Total Weight: {total_weight}
// Threshold: {strategy.signal_logic.threshold_percent}%''')
        
        # Join all code parts
        full_code = '\n'.join(code_parts)
        
        # Debug: Log code length to ensure it's complete
        print(f"[PineScriptGenerator] Generated code length: {len(full_code)} characters")
        print(f"[PineScriptGenerator] Code parts count: {len(code_parts)}")
        print(f"[PineScriptGenerator] Indicators: {len(indicator_vars)}")
        print(f"[PineScriptGenerator] Has signal logic: {'SIGNAL LOGIC' in full_code}")
        print(f"[PineScriptGenerator] Has entry/exit: {'ENTRY/EXIT' in full_code}")
        print(f"[PineScriptGenerator] Has plotting: {'PLOTTING' in full_code}")
        
        return PineScriptExport(
            code=full_code,
            strategy_name=strategy.name,
            indicators_used=indicators_used,
            version=strategy_version,
            backtest_info=backtest_result
        )
    
    @staticmethod
    def _generate_indicator_code(ind_type: str, config: dict, var_id: str) -> str:
        """
        Generate Pine Script code for specific indicator
        
        Args:
            ind_type: Type of indicator (RSI, MACD, etc.)
            config: Configuration dictionary with indicator parameters
            var_id: Unique variable identifier for this indicator instance
            
        Returns:
            Pine Script code string with:
            - Indicator calculation
            - Bullish signal variable ({var_id}_bull)
            - Bearish signal variable ({var_id}_bear)
            - Optional plot statements
        """
        
        # === MOMENTUM INDICATORS ===
        if ind_type == "RSI":
            period = config.get('period', 14)
            oversold = config.get('oversold', 30)
            overbought = config.get('overbought', 70)
            return f'''
{var_id}_val = ta.rsi(close, {period})
{var_id}_bull = {var_id}_val < {oversold}
{var_id}_bear = {var_id}_val > {overbought}'''
        
        elif ind_type == "MACD":
            fast = config.get('fast_period', 12)
            slow = config.get('slow_period', 26)
            signal = config.get('signal_period', 9)
            return f'''
[{var_id}_line, {var_id}_signal, _] = ta.macd(close, {fast}, {slow}, {signal})
{var_id}_bull = {var_id}_line > {var_id}_signal
{var_id}_bear = {var_id}_line < {var_id}_signal'''
        
        elif ind_type == "Stochastic":
            k_period = config.get('k_period', 14)
            d_period = config.get('d_period', 3)
            smooth = config.get('smooth', 3)
            oversold = config.get('oversold', 20)
            overbought = config.get('overbought', 80)
            return f'''
{var_id}_k = ta.sma(ta.stoch(close, high, low, {k_period}), {smooth})
{var_id}_d = ta.sma({var_id}_k, {d_period})
{var_id}_bull = {var_id}_k < {oversold}
{var_id}_bear = {var_id}_k > {overbought}'''
        
        elif ind_type == "CCI":
            period = config.get('period', 20)
            overbought = config.get('overbought', 100)
            oversold = config.get('oversold', -100)
            return f'''
{var_id}_val = ta.cci(close, {period})
{var_id}_bull = {var_id}_val < {oversold}
{var_id}_bear = {var_id}_val > {overbought}'''
        
        elif ind_type == "MFI":
            period = config.get('period', 14)
            oversold = config.get('oversold', 20)
            overbought = config.get('overbought', 80)
            return f'''
// MFI - Money Flow Index
{var_id}_val = ta.mfi(close, {period})
{var_id}_bull = {var_id}_val < {oversold}
{var_id}_bear = {var_id}_val > {overbought}
{var_id}_neutral = {var_id}_val >= {oversold} and {var_id}_val <= {overbought}'''
        
        elif ind_type == "ROC":
            period = config.get('period', 12)
            return f'''
{var_id}_val = ta.roc(close, {period})
{var_id}_bull = {var_id}_val > 0
{var_id}_bear = {var_id}_val < 0'''
        
        elif ind_type == "VROC":
            period = config.get('period', 14)
            return f'''
{var_id}_val = (volume - volume[{period}]) / volume[{period}] * 100
{var_id}_bull = {var_id}_val > 0
{var_id}_bear = {var_id}_val < 0'''
        
        elif ind_type == "RVI":
            period = config.get('period', 10)
            return f'''
{var_id}_val = (close - open) / (high - low)
{var_id}_sma = ta.sma({var_id}_val, {period})
{var_id}_bull = {var_id}_sma > 0
{var_id}_bear = {var_id}_sma < 0'''
        
        elif ind_type == "Awesome_Oscillator":
            fast = config.get('fast_period', 5)
            slow = config.get('slow_period', 34)
            return f'''
{var_id}_val = ta.sma(hl2, {fast}) - ta.sma(hl2, {slow})
{var_id}_bull = {var_id}_val > {var_id}_val[1]
{var_id}_bear = {var_id}_val < {var_id}_val[1]'''
        
        elif ind_type == "Momentum":
            period = config.get('period', 10)
            return f'''
{var_id}_val = close - close[{period}]
{var_id}_bull = {var_id}_val > 0
{var_id}_bear = {var_id}_val < 0'''
        
        # === TREND INDICATORS ===
        elif ind_type in ["EMA_50", "EMA_200", "EMA_12", "EMA_26"]:
            period = config.get('period', int(ind_type.split('_')[1]) if '_' in ind_type else 50)
            return f'''
{var_id}_val = ta.ema(close, {period})
{var_id}_bull = close > {var_id}_val
{var_id}_bear = close < {var_id}_val'''
        
        elif ind_type == "Triple_EMA":
            fast = config.get('fast_period', 5)
            medium = config.get('medium_period', 10)
            slow = config.get('slow_period', 20)
            return f'''
{var_id}_fast = ta.ema(close, {fast})
{var_id}_medium = ta.ema(close, {medium})
{var_id}_slow = ta.ema(close, {slow})
{var_id}_bull = {var_id}_fast > {var_id}_medium and {var_id}_medium > {var_id}_slow
{var_id}_bear = {var_id}_fast < {var_id}_medium and {var_id}_medium < {var_id}_slow
plot({var_id}_fast, "EMA {fast}", color.blue)
plot({var_id}_medium, "EMA {medium}", color.orange)
plot({var_id}_slow, "EMA {slow}", color.red)'''
        
        elif ind_type == "ADX":
            period = config.get('period', 14)
            threshold = config.get('threshold', 25)
            return f'''
[{var_id}_plus, {var_id}_minus, {var_id}_val] = ta.dmi({period}, {period})
{var_id}_bull = {var_id}_plus > {var_id}_minus and {var_id}_val > {threshold}
{var_id}_bear = {var_id}_minus > {var_id}_plus and {var_id}_val > {threshold}'''
        
        elif ind_type == "SuperTrend":
            period = config.get('period', 10)
            multiplier = config.get('multiplier', 3.0)
            return f'''
[{var_id}_val, {var_id}_dir] = ta.supertrend({multiplier}, {period})
{var_id}_bull = {var_id}_dir < 0
{var_id}_bear = {var_id}_dir > 0
plot({var_id}_val, "SuperTrend", {var_id}_dir < 0 ? color.green : color.red)'''
        
        # === VOLATILITY INDICATORS ===
        elif ind_type == "Bollinger_Bands":
            period = config.get('period', 20)
            std = config.get('std_dev', 2.0)
            return f'''
{var_id}_basis = ta.sma(close, {period})
{var_id}_dev = ta.stdev(close, {period})
{var_id}_upper = {var_id}_basis + {var_id}_dev * {std}
{var_id}_lower = {var_id}_basis - {var_id}_dev * {std}
{var_id}_bull = close < {var_id}_lower
{var_id}_bear = close > {var_id}_upper
plot({var_id}_upper, "BB Upper", color.red)
plot({var_id}_basis, "BB Mid", color.gray)
plot({var_id}_lower, "BB Lower", color.green)'''
        
        elif ind_type == "ATR":
            period = config.get('period', 14)
            atr_threshold = config.get('atr_threshold', 0.5)
            return f'''
// ATR Indicator
{var_id}_val = ta.atr({period})
{var_id}_high = {var_id}_val > {atr_threshold}
{var_id}_bull = {var_id}_val > {var_id}_val[1]
{var_id}_bear = {var_id}_val < {var_id}_val[1]'''
        
        elif ind_type == "Donchian":
            period = config.get('period', 20)
            return f'''
{var_id}_upper = ta.highest(high, {period})
{var_id}_lower = ta.lowest(low, {period})
{var_id}_mid = ({var_id}_upper + {var_id}_lower) / 2
{var_id}_bull = close > {var_id}_mid
{var_id}_bear = close < {var_id}_mid'''
        
        # === VOLUME INDICATORS ===
        elif ind_type == "Volume_MA":
            period = config.get('period', 20)
            return f'''
{var_id}_val = ta.sma(volume, {period})
{var_id}_bull = volume > {var_id}_val
{var_id}_bear = volume < {var_id}_val'''
        
        elif ind_type == "OBV":
            return f'''
{var_id}_val = ta.obv
{var_id}_bull = {var_id}_val > {var_id}_val[1]
{var_id}_bear = {var_id}_val < {var_id}_val[1]'''
        
        # === SUPPORT/RESISTANCE ===
        elif ind_type == "Pivot_Points":
            return f'''
{var_id}_pivot = (high[1] + low[1] + close[1]) / 3
{var_id}_r1 = 2 * {var_id}_pivot - low[1]
{var_id}_s1 = 2 * {var_id}_pivot - high[1]
{var_id}_bull = close > {var_id}_pivot
{var_id}_bear = close < {var_id}_pivot'''
        
        # === ADVANCED INDICATORS ===
        elif ind_type == "Fibonacci":
            lookback = config.get('lookback', 64)
            tolerance = config.get('tolerance', 0.002)
            return f'''
// Fibonacci Retracement
{var_id}_high = ta.highest(high, {lookback})
{var_id}_low = ta.lowest(low, {lookback})
{var_id}_diff = {var_id}_high - {var_id}_low

// Fibonacci Levels
{var_id}_0 = {var_id}_high
{var_id}_236 = {var_id}_high - {var_id}_diff * 0.236
{var_id}_382 = {var_id}_high - {var_id}_diff * 0.382
{var_id}_50 = {var_id}_high - {var_id}_diff * 0.5
{var_id}_618 = {var_id}_high - {var_id}_diff * 0.618
{var_id}_786 = {var_id}_high - {var_id}_diff * 0.786
{var_id}_100 = {var_id}_low

// Signal detection
{var_id}_tolerance = {tolerance}
{var_id}_near_382 = math.abs(close - {var_id}_382) / close <= {var_id}_tolerance
{var_id}_near_50 = math.abs(close - {var_id}_50) / close <= {var_id}_tolerance
{var_id}_near_618 = math.abs(close - {var_id}_618) / close <= {var_id}_tolerance

{var_id}_bull = ({var_id}_near_382 or {var_id}_near_50 or {var_id}_near_618) and close > close[5]
{var_id}_bear = ({var_id}_near_382 or {var_id}_near_50) and close < close[5]

// Plot levels
plot({var_id}_0, "Fib 0.0", color=color.gray, linewidth=1)
plot({var_id}_236, "Fib 0.236", color=color.red, linewidth=1)
plot({var_id}_382, "Fib 0.382", color=color.orange, linewidth=1)
plot({var_id}_50, "Fib 0.5", color=color.yellow, linewidth=2)
plot({var_id}_618, "Fib 0.618", color=color.green, linewidth=1)
plot({var_id}_786, "Fib 0.786", color=color.blue, linewidth=1)
plot({var_id}_100, "Fib 1.0", color=color.gray, linewidth=1)'''
        
        elif ind_type == "Ichimoku":
            tenkan = config.get('tenkan_period', 9)
            kijun = config.get('kijun_period', 26)
            senkou = config.get('senkou_b_period', 52)
            return f'''
{var_id}_tenkan = (ta.highest(high, {tenkan}) + ta.lowest(low, {tenkan})) / 2
{var_id}_kijun = (ta.highest(high, {kijun}) + ta.lowest(low, {kijun})) / 2
{var_id}_senkou_a = ({var_id}_tenkan + {var_id}_kijun) / 2
{var_id}_senkou_b = (ta.highest(high, {senkou}) + ta.lowest(low, {senkou})) / 2
{var_id}_cloud_top = math.max({var_id}_senkou_a, {var_id}_senkou_b)
{var_id}_bull = close > {var_id}_cloud_top and ta.crossover({var_id}_tenkan, {var_id}_kijun)
{var_id}_bear = close < {var_id}_cloud_top and ta.crossunder({var_id}_tenkan, {var_id}_kijun)
plot({var_id}_tenkan, "Tenkan", color.red)
plot({var_id}_kijun, "Kijun", color.blue)'''
        
        elif ind_type == "Candlestick_Patterns":
            return f'''
// Candlestick Patterns
{var_id}_body = math.abs(close - open)
{var_id}_range = high - low
{var_id}_upper = high - math.max(open, close)
{var_id}_lower = math.min(open, close) - low
{var_id}_hammer = {var_id}_lower > {var_id}_body * 2 and {var_id}_upper < {var_id}_body * 0.3
{var_id}_shoot = {var_id}_upper > {var_id}_body * 2 and {var_id}_lower < {var_id}_body * 0.3
{var_id}_bull_engulf = close[1] < open[1] and close > open and close > open[1] and open < close[1]
{var_id}_bear_engulf = close[1] > open[1] and close < open and close < open[1] and open > close[1]
{var_id}_bull = {var_id}_hammer or {var_id}_bull_engulf
{var_id}_bear = {var_id}_shoot or {var_id}_bear_engulf
plotshape({var_id}_hammer, "Hammer", shape.labelup, location.belowbar, color.green, size=size.tiny)
plotshape({var_id}_shoot, "Shooting Star", shape.labeldown, location.abovebar, color.red, size=size.tiny)'''
        
        elif ind_type == "ICT_Concepts":
            return f'''
// ICT Concepts - Fair Value Gap
{var_id}_bull_fvg = low > high[2]
{var_id}_bear_fvg = high < low[2]
{var_id}_range_high = ta.highest(high, 50)
{var_id}_range_low = ta.lowest(low, 50)
{var_id}_equilibrium = ({var_id}_range_high + {var_id}_range_low) / 2
{var_id}_premium = close > {var_id}_equilibrium + ({var_id}_range_high - {var_id}_range_low) * 0.25
{var_id}_discount = close < {var_id}_equilibrium - ({var_id}_range_high - {var_id}_range_low) * 0.25
{var_id}_bull = {var_id}_bull_fvg or {var_id}_discount
{var_id}_bear = {var_id}_bear_fvg or {var_id}_premium
bgcolor({var_id}_premium ? color.new(color.red, 95) : na)
bgcolor({var_id}_discount ? color.new(color.green, 95) : na)'''
        
        else:
            # Generic fallback
            return f'''
// {ind_type} - Manual implementation needed
{var_id}_bull = false
{var_id}_bear = false'''


# Global instance
pine_script_generator = PineScriptGenerator()
